spring.application.name=bookStore

application.security.jwt.secrectKey=TXlPbmxpbmVCb29rU3RvcmVBcHBsaWNhdGlvbjk3MzA=
application.security.jwt.expirationTime=890000
application.baseurl = api/v1

spring.datasource.url=jdbc:mysql://localhost:3306/bookStore
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
